[package]
name = "pvt"
version = "0.1.0"
edition = "2021"

description = "Python Version Tamer"
repository = "https://github.com/nihaals/pvt"
license = "GPL-3.0-only"

[dependencies]
clap = { version = "3", features = ["derive"] }
clap_complete_command = "0.3"
